name: New Media Added

on:
  repository_dispatch:
    types: [arr-import]

jobs:
  movie:
    if: ${{ github.event.client_payload.instanceName == 'Radarr' }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          title="${{ github.event.client_payload.movie.title }}"
          encoded_title="$(echo "$title" | sed -e 's/ /+/g' -e 's/&/%26/g')"
          release_year="${{ github.event.client_payload.remoteMovie.year }}"
          tmdb_id="${{ github.event.client_payload.remoteMovie.tmdbId }}"
          tpdb_search="https://theposterdb.com/search?term=$encoded_title&section=movies"

          lower_title="${title,,}"  # convert to lowercase for comparison
          sort_title="$title"
          for article in "a " "an " "the "; do
              if [[ "$lower_title" == "$article"* ]]; then
                  sort_title="${title:${#article}}"
                  break
              fi
          done
          
          sort_title=$(echo "$sort_title" | iconv -f UTF-8 -t ASCII//TRANSLIT)
          
          echo $tmdb_id
          echo $title
          echo $release_year
          echo $sort_title
          echo $tpdb_search

  show:
    if: ${{ github.event.client_payload.instanceName == 'Sonarr' }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Show!"
        
