name: New Media Added

on:
  repository_dispatch:
    types: [arr-import]

jobs:
  movie:
    if: ${{ github.event.client_payload.instanceName == "Radarr" }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Movie!"

  show:
    if: ${{ github.event.client_payload.instanceName == "Sonarr" }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Show!"
        
