name: Find Missing Posters

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *' # 4 times a day

permissions:
  id-token: write
  contents: read
  issues: write

env:
  MOVIE_METADATA_FILE: movie_metadata.yml
  SHOW_METADATA_FILE: show_metadata.yml

jobs:
  update:
    name: Find Missing Posters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4.2.2

      - name: Set-Up Python
        id: setup-python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13.3

      - name: Install Requirements
        id: install-requirements
        uses: py-actions/py-dependency-install@v4
        with:
          path: scripts/requirements.txt

      - name: Run Metadata File Update Script
        id: run-script
        run: |
          python3 scripts/kometa_missing_poster_find.py --movie_file ${{ env.MOVIE_METADATA_FILE }} --show_file ${{ env.SHOW_METADATA_FILE }}

      - name: Create Job Summary
        run: |
          echo "# Movies" >> $GITHUB_STEP_SUMMARY
          cat poster_report_movies.md >> $GITHUB_STEP_SUMMARY
          echo "# Shows" >> $GITHUB_STEP_SUMMARY
          cat poster_report_shows.md >> $GITHUB_STEP_SUMMARY
          
        


      
